version: "3.8"

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: vs_db
      POSTGRES_USER: vs_user
      POSTGRES_PASSWORD: vs_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vs_user -d vs_db"]
      interval: 5s
      retries: 5

  api:
    build: .
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "stockago.local:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"
    command:
      - /bin/sh
      - -c
      - |
        if [ "$${UVICORN_RELOAD}" = "true" ]; then
          uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        else
          uvicorn app.main:app --host 0.0.0.0 --port 8000
        fi
    volumes:
      - .:/app:cached

volumes:
  pgdata: